pull_request_rules:
  - name: Automatic merge for updates
    conditions:
      - "head~=update/"
      - "author=hnaderi"
      - "check-status = build-home"
      - "check-status = build-nixos"
    actions:
      merge:
        method: rebase
