name: Home

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'notes/**'
      - '.gitignore'
      - 'outputs/nixos-conf.nix'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v15

      - name: "Build Home Manager config 🏠"
        run: |
          nix build .#homeConfigurations.hnaderi.activationPackage
