name: Home

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'notes/**'
      - '.gitignore'
      - 'outputs/nixos-conf.nix'

jobs:
  build-home:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v15

      - name: "Build Home Manager config 🏠"
        run: |
          nix build .#homeConfigurations.hnaderi.activationPackage
