name: NixOS

on:
  pull_request:
    paths-ignore:
      - 'home/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'notes/**'
      - '.gitignore'
      - 'home/**'
      - 'outputs/home-conf.nix'

jobs:
  build-nixos:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v15

      - name: "Build NixOS config ❄️"
        run: |
          nix build .#nixosConfigurations.behemoth.config.system.build.toplevel
